Repository OCA/connector-jira, pull requests merged in 2020-08, with the labels that each got.

#47 [11.0] connector_jira: Add epic link on epic
  connector_jira/models/account_analytic_line/importer.py
  connector_jira/models/jira_backend/common.py
  connector_jira/tests/test_import_analytic_line.py
  connector_jira/views/jira_backend_views.xml
Labels: approved, bot is merging ⏳

#44 [11.0] connector_jira_servicedesk: Add servicedesk_issue_url
  connector_jira_servicedesk/models/account_analytic_line/__init__.py
  connector_jira_servicedesk/models/account_analytic_line/common.py
  connector_jira_servicedesk/models/jira_backend/common.py
  connector_jira_servicedesk/models/project_project/common.py
  connector_jira_servicedesk/views/project_project_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#52 [12.0][IMP] connector_jira: Add epic link on epic
  connector_jira/models/account_analytic_line/importer.py
  connector_jira/models/jira_backend/common.py
  connector_jira/tests/test_import_analytic_line.py
  connector_jira/views/jira_backend_views.xml
Labels: bot is merging ⏳
